package org.b3log.util;

/**
 * @author Zhang Yu
 * Date: 17年12月13日
 * Email: 2895205695@qq.com
 */
public class CommonValues {
    public static final String REPLACE = "#_#";
    public static final String TITLE = "/**\n" +
            " * @author Zhang Yu\n" +
            //TODO 日期需要动态生成
            " * Date: 17年12月13日\n" +
            " * Generated by MybatisMapper\n" +
            " */\n";

    public static final String XML_TEMPLATE="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<!DOCTYPE mapper PUBLIC \"-//mybatis.org//DTD Mapper 3.0//EN\" \"http://mybatis.org/dtd/mybatis-3-mapper.dtd\">\n" +
            "<mapper namespace=\""+REPLACE+"\">\n" +
            "  <sql id=\"COLUMNS\">\n" +
            "    "+REPLACE+"\n" +
            "  </sql>\n" +
            "</mapper>";

    public static final String MAPPER_TEMPLATE = "package "+REPLACE+";\n" +
            "import org.apache.ibatis.annotations.Mapper;\n" +
            "\n" +
            TITLE +
            "@Mapper\n" +
            "public interface "+REPLACE+" {\n" +
            "   \n" +
            "}\n";
}
